name: Release
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            host: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            host: ubuntu-latest
          - target: aarch64-apple-darwin
            use-cross: false
            host: macos-latest
          - target: x86_64-apple-darwin
            use-cross: false
            host: macos-latest
          - target: x86_64-pc-windows-gnu
            host: ubuntu-latest
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          profile: release

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        id: download-artifacts
        with:
          path: artifacts/
          merge-multiple: true
      - name: Determine version
        run: echo "version=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[] | select(.name == "wg-nord") | .version')" >> $GITHUB_ENV
        shell: bash
      - name: Release
        run: |
          gh release create \
          --latest \
          --generate-notes \
          "v${{ env.version }}" \
          artifacts/*
